index: 
    path: /
    controller: App\Controller\Home::homepage

login:
    path: /login
    controller: App\Controller\Home::login

consult:
    path: /consult/{var}
    controller: App\Controller\Home::consult